apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: {{ .Values.autoscaling.metricName }}
          selector:
            matchLabels:
              service: {{ .Release.Name }}
              namespace: {{ .Release.Namespace }}
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.averageValue }}
